<?php
/*
 * ************** CAUTION **************
 *
 * DO NOT EDIT THIS FILE as it will be overridden by Central as part of
 * the installation/update process.
 *
 * ************** CAUTION **************
 */

$API->config(array(
    'database.host' => 'your_host',
    'database.name' => 'your_dbname',
    'database.user' => 'your_dbuser',
    'database.pass' => 'your_dbpassword',
    'site.hash' => 'ahashwillbegenerated'
));

// Adive Framework Content Type
$API->contentType('text/html; charset=utf-8');

// PDO Database connection
if($API->config('database.host')!='your_host'){
$db = new PDO('mysql:host=' . $API->config('database.host') . 
             ';dbname=' . $API->config('database.name') . 
             ';charset=utf8', $API->config('database.user'), $API->config('database.pass')); 
} else {
$db= null;
}
